stages:
  - build_builder
  - build_dll
  - build_wpf
  - build_patcher
  - build_unpatcher
  - autoupdate_zip
  - move_files

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Release\Builder.exe Builder.exe
  artifacts:
    paths:
    - Builder.exe
    expire_in: 1 day
  only:
    - dev
    - release

build_dll:
  stage: build_dll
  script:
   - .\Builder.exe builddll dlls=$dlls
  artifacts:
   paths:
   - ModLoader\bin\Release\ModLoader.dll
   - ModLoader\bin\Release\ModLoader.xml
   - Core\bin\Release\netstandard2.0\Core.dll
   expire_in: 1 day
  only:
    - dev
    - release

build_wpf:
  stage: build_wpf
  script:
   - .\Builder.exe buildwpf dlls=$dlls
  artifacts:
   paths:
   - Launcher\bin\Release\net5.0-windows\win-x64\publish\Launcher.exe
   expire_in: 1 day
  only:
    - dev
    - release

build_patcher:
  stage: build_patcher
  script:
    - .\Builder.exe buildpatcher dlls=$dlls
  artifacts:
    paths:
      - VTPatcher\bin\Release\VTPatcher.dll
    expire_in: 1 day
  only:
    - dev
    - release

build_unpatcher:
  stage: build_unpatcher
  script:
    - .\Builder.exe buildunpatcher dlls=$dlls
  artifacts:
    paths:
      - UnPatcher\bin\Release\UnPatcher.exe
    expire_in: 1 day
  only:
    - dev
    - release
  

autoupdate_zip:
  stage: autoupdate_zip
  script:
   - .\Builder.exe autoupdatezip template=$template
  artifacts:
   paths:
   - autoupdate.zip
   expire_in: 1 day
  only:
    - dev
    - release

move_files:
  stage: move_files
  script:
   - .\Builder.exe move
  only:
    - dev
    - release