stages:
  - run

run:
  stage: run
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Release\Builder.exe Builder.exe
   - Builder.exe -template=A:\Code\VTOLVR-ModLoader-Gitlab\ModLoader\template -dlls=A:\Code\VTOLVR-ModLoader-Gitlab\ModLoader\dll