stages:
  - build_builder
  - run_builder

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release

run_builder:
  stage: run_builder
  script:
   - echo 'Running Builder.exe'
   - Builder.exe