stages:
  - build_builder
  - build_dll
  - build_wpf
  - build_updater
  - zip
  - build_installer

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Release\Builder.exe Builder.exe
  artifacts:
    paths:
    - Builder.exe
    expire_in: 1 day

build_dll:
  stage: build_dll
  script:
   - Builder.exe builddll dlls=A:\Code\VTOLVR-ModLoader-Gitlab\ModLoader\dll

build_wpf:
  stage: build_wpf
  script:
   - Builder.exe buildwpf

build_updater:
  stage: build_updater
  script:
   - Builder.exe buildupdater

zip:
  stage: zip
  script:
   - Builder.exe zip

build_installer:
  stage: build_installer
  script:
   - Builder.exe buildinstaller