.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809


stages:
  - build

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
  - reg.exe query 'HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.5' /v MSBuildToolsPath
