stages:
  - build_builder
  - build_dll
  - build_wpf
  - build_updater
  - zip
  - build_installer
  - autoupdate_zip
  - move_files

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Debug
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Debug\Builder.exe Builder.exe
  artifacts:
    paths:
    - Builder.exe
    expire_in: 1 day

build_dll:
  stage: build_dll
  script:
   - .\Builder.exe builddll dlls=$dlls
  artifacts:
   paths:
   - ModLoader\bin\Debug\ModLoader.dll
   - ModLoader\bin\Debug\ModLoader.xml
   - Core\bin\Debug\Core.dll
   expire_in: 1 day

build_wpf:
  stage: build_wpf
  script:
   - .\Builder.exe buildwpf dlls=$dlls
  artifacts:
   paths:
   - VTOLVR-ModLoader\bin\Debug\VTOLVR-ModLoader.exe
   expire_in: 1 day

build_updater:
  stage: build_updater
  script:
   - .\Builder.exe buildupdater dlls=$dlls
  artifacts:
   paths:
   - Updater\bin\Debug\Updater.exe
   expire_in: 1 day

zip:
  stage: zip
  script:
   - .\Builder.exe zip template=$template
  artifacts:
   paths:
   - Installer\Resources\ModLoader.zip
   expire_in: 1 day

build_installer:
  stage: build_installer
  script:
   - .\Builder.exe buildinstaller
  artifacts:
   paths:
   - Installer\bin\Debug\Installer.exe
   expire_in: 1 day

autoupdate_zip:
  stage: autoupdate_zip
  script:
   - .\Builder.exe autoupdatezip template=$template
  artifacts:
   paths:
   - autoupdate.zip
   expire_in: 1 day

move_files:
  stage: move_files
  script:
   - .\Builder.exe move