.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
  - echo 'Building Mod Loader'
  - msbuild ./ModLoader/ModLoader
