stages:
  - build_builder
  - build_wpf
  - build_updater
  - zip
  - build_installer

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Release\Builder.exe Builder.exe

build_dll:
  stage: build_dll
  script:
   - Builder.exe builddll dlls=A:\Code\VTOLVR-ModLoader-Gitlab\ModLoader\dll

build_wpf:
  stage: build_wpf
  script:
   - Builder.exe buildwpf

build_updater:
  stage: build_updater
  script:
   - Builder.exe buildupdater

zip:
  stage: zip
  script:
   - Builder.exe zip

build_installer:
  stage: build_installer
  script:
   - Builder.exe buildinstaller

testing:
  stage: testing
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Release\Builder.exe Builder.exe
   - Builder.exe template=A:\Code\VTOLVR-ModLoader-Gitlab\ModLoader\template dlls=A:\Code\VTOLVR-ModLoader-Gitlab\ModLoader\dll