stages:
  - build_builder
  - build_dll
  - build_wpf
  - build_patcher
  - zip
  - build_installer
  - autoupdate_zip
  - move_files

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Running Builder.exe'
   - cd ..
   - MOVE Builder\bin\Release\Builder.exe Builder.exe
  artifacts:
    paths:
    - Builder.exe
    expire_in: 1 day

build_dll:
  stage: build_dll
  script:
   - .\Builder.exe builddll dlls=$dlls
  artifacts:
   paths:
   - ModLoader\bin\Release\ModLoader.dll
   - ModLoader\bin\Release\ModLoader.xml
   - CoreCore\bin\Release\net5.0\CoreCore.dll
   expire_in: 1 day

build_wpf:
  stage: build_wpf
  script:
   - .\Builder.exe buildwpf dlls=$dlls
  artifacts:
   paths:
   - LauncherCore\bin\Release\net5.0-windows\win-x64\publish\LauncherCore.exe
   expire_in: 1 day

build_patcher:
  stage: build_patcher
  script:
    - .\Builder.exe buildpatcher dlls=$dlls
  artifacts:
    paths:
      - VTPatcher\bin\Release\VTPatcher.dll
    expire_in: 1 day
    
    
    
sign_files:
  stage: sign_files
  script:
    - .\Builder.exe sign
  artifacts:
    paths:
      - ModLoader\bin\Release\ModLoader.dll
      - ModLoader\bin\Release\ModLoader.xml
      - CoreCore\bin\Release\net5.0\CoreCore.dll
      - LauncherCore\bin\Release\net5.0-windows\win-x64\publish\LauncherCore.exe
      - VTPatcher\bin\Release\VTPatcher.dll
    expire_in: 1 day
  allow_failure: true
  

autoupdate_zip:
  stage: autoupdate_zip
  script:
   - .\Builder.exe autoupdatezip template=$template
  artifacts:
   paths:
   - autoupdate.zip
   expire_in: 1 day

move_files:
  stage: move_files
  script:
   - .\Builder.exe move