.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

image: mcr.microsoft.com/dotnet/framework/sdk:4.8

stages:
  - build

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
  - echo 'Building Mod Loader'
  - dotnet ModLoader/ModLoader
