stages:
  - build_builder
  - run_builder

build_builder:
  stage: build_builder
  script:
   - echo 'Building Build.exe'
   - cd Build
   - dotnet build --configuration Release
   - echo 'Moving Build.exe to root'
   - cd ..
   - MOVE Build/bin/Release/Build.exe Build.exe

run_builder:
  stage: run_builder
  script:
   - echo 'Running Builder.exe'
   - Build.exe