stages:
  - build_builder
  - run_builder

build_builder:
  stage: build_builder
  script:
   - echo 'Building Builder.exe'
   - cd Builder
   - dotnet build --configuration Release
   - echo 'Moving Builder.exe to root'
   - cd ..
   - MOVE Builder/bin/Release/Builder.exe Builder.exe

run_builder:
  stage: run_builder
  script:
   - echo 'Running Builder.exe'
   - Builder.exe