//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTOLVR_ModLoader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTOLVR_ModLoader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Campaigns&quot;: [
        ///    {
        ///      &quot;CampaignID&quot;: &quot;av42cTheIsland&quot;,
        ///      &quot;CampaignName&quot;: &quot;The Island&quot;,
        ///      &quot;Description&quot;: &quot;The Island campaign.&quot;,
        ///      &quot;Vehicle&quot;: &quot;AV-42C&quot;,
        ///      &quot;Scenarios&quot;: [
        ///        {
        ///          &quot;Id&quot;: &quot;01_preparations&quot;,
        ///          &quot;Name&quot;: &quot;Preparations&quot;,
        ///          &quot;Description&quot;: &quot;Help make preparations to defend the island. Transport personnel to coastal SAM site.&quot;,
        ///          &quot;CampaignOrderIdx&quot;: 0
        ///        },
        ///        {
        ///          &quot;Id&quot;: &quot;02_minesweeper&quot;,
        ///          &quot;Name&quot;: &quot;Mines [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CampaignsJsonString {
            get {
                return ResourceManager.GetString("CampaignsJsonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap image_not_found {
            get {
                object obj = ResourceManager.GetObject("image_not_found", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] vtolvr_mod_boilerplate_master {
            get {
                object obj = ResourceManager.GetObject("vtolvr_mod_boilerplate_master", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
